version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: mf_postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migracaoBancoDeDados:/docker-entrypoint-initdb.d
    networks:
      - financas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: mf_adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - financas-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:

networks:
  financas-network:
    driver: bridge
